version: '3.4'

services:
  api:
    image: api
    build:
      context: apps/api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: apart-connect
    ports:
      - 5005:5005
    volumes:
      - type: bind
        source: ./apps/api
        target: /usr/src/app
    depends_on:
      - db
    networks:
      - app-network
  # PostgreSQL database
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apart-connect

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  app-network:
    driver: bridge
